[workspace]
members = [
    "components/chainhook-sdk",
    "components/chainhook-cli",
    "components/chainhook-types-rs",
]
default-members = ["components/chainhook-cli", "components/chainhook-sdk"]
resolver = "2"

[patch.crates-io]
stacks-codec = { git = "https://github.com/hirosystems/clarinet.git", rev = "25d628f3bd5b3f05696b13ad97f1794a5a71e067" }
