##
## Bumps the Chainhook version listed on various package managers.
##

name: Package Version Bump
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the release.'
        required: true
  repository_dispatch:
    types:
      - released

jobs:
  winget_komac:
    name: Publish to Winget via Komac
    runs-on: windows-latest
    steps:
      - name: Winget version bump
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: HiroSystems.Chainhook
          max-versions-to-keep: 5 # keep only latest 5 versions
          token: ${{ secrets.GH_TOKEN }}
